
[%autowidth.stretch]
|===

3+^h| abstract  *class EL_FEATURE_REF*

h|*Description*
2+a|A reference that is scoped by a containing entity and requires a context qualifier if it
is not the currently scoping entity.

h|*Inherit*
2+|xref:languages:bmm-gen.adoc#_class_el_value_generator[EL_VALUE_GENERATOR]

h|
2+^h|*Feature Group "access"*

h|prop +
  0..1
|*scoper*: xref:languages:bmm-gen.adoc#_class_el_value_generator[EL_VALUE_GENERATOR]
a|Scoping expression, which must be a `EL_VALUE_GENERATOR`.

h| func
|*reference* : xref:representation:builtin_types-gen.adoc#_class_string[String]
a|Generated full reference name, consisting of scoping elements and `name` concatenated
using dot notation.

h|prop +
  
|*is_writable*: xref:representation:builtin_types-gen.adoc#_class_boolean[Boolean]
a|

h|prop +
  
|*name*: xref:representation:builtin_types-gen.adoc#_class_string[String]
a|Name used to represent the reference or other entity.

h| func
|*eval_type* : xref:languages:bmm-gen.adoc#_class_bmm_type[BMM_TYPE]
a|Meta-type of expression entity used in type-checking and evaluation.

Effected in descendants.

h| func
|*is_boolean* : xref:representation:builtin_types-gen.adoc#_class_boolean[Boolean] +
 +
  *post_cond* +
    result_validity: Result = eval_type().equal(BMM_MODEL.boolean_type_definition());

a|True if `eval_type` is notionally Boolean (i.e. a `BMM_SIMPLE_TYPE` with `type_name()`
= `Boolean`).

|===
