
[%autowidth.stretch]
|===

3+^h|  *class EL_TUPLE*

h|*Description*
2+a|Defines an array of optionally named items each of any type.

h|*Inherit*
2+|xref:languages:bmm-gen.adoc#_class_el_expression[EL_EXPRESSION]

h|
2+^h|*Feature Group "access"*

h|prop +
  0..1
|*items*: xref:representation:builtin_types-gen.adoc#_class_list[List]<xref:languages:bmm-gen.adoc#_class_el_tuple_item[EL_TUPLE_ITEM]>
a|Items in the tuple, potentially with names. Typical use is to represent an argument list
to routine call.

h|prop +
  
|*type*: xref:languages:bmm-gen.adoc#_class_bmm_tuple_type[BMM_TUPLE_TYPE]
a|Static type inferred from literal value.

h| func
|*eval_type* : xref:languages:bmm-gen.adoc#_class_bmm_type[BMM_TYPE]
a|Return `type`.

h| func
|*is_boolean* : xref:representation:builtin_types-gen.adoc#_class_boolean[Boolean] +
 +
  *post_cond* +
    result_validity: Result = eval_type().equal(BMM_MODEL.boolean_type_definition());

a|True if `eval_type` is notionally Boolean (i.e. a `BMM_SIMPLE_TYPE` with `type_name()`
= `Boolean`).

|===
