
[%autowidth.stretch]
|===

3+^h|  *class EL_UNARY_OPERATOR*


h|
2+^h|*Feature Group "access"*

h|prop +
  
|*operand*: xref:languages:bmm-gen.adoc#_class_el_expression[EL_EXPRESSION]
a|Operand node.

h|prop +
  0..1
|*precedence_overridden*: xref:representation:builtin_types-gen.adoc#_class_boolean[Boolean]
a|True if the natural precedence of operators is overridden in the expression represented by
this node of the expression tree. If True, parentheses should be introduced around the
totality of the syntax expression corresponding to this operator node and its operands.

h|prop +
  0..1
|*symbol*: xref:representation:builtin_types-gen.adoc#_class_string[String]
a|The symbol actually used in the expression, or intended to be used for serialisation. Must
be a member of `OPERATOR_DEF._symbols`.

h|prop +
  
|*call*: xref:languages:bmm-gen.adoc#_class_el_function_call[EL_FUNCTION_CALL]
a|Function call equivalent to this operator expression, inferred by matching operator
against functions defined in interface of principal operand.

h| func
|*operator_definition* : xref:languages:bmm-gen.adoc#_class_bmm_operator[BMM_OPERATOR]
a|Operator definition derived from `definition.operator_definition()`.

h| func
|*equivalent_call* : xref:languages:bmm-gen.adoc#_class_el_function_call[EL_FUNCTION_CALL]
a|Function call equivalent to this operator.

h| func
|*eval_type* : xref:languages:bmm-gen.adoc#_class_bmm_type[BMM_TYPE]
a|Meta-type of expression entity used in type-checking and evaluation.

Effected in descendants.

h| func
|*is_boolean* : xref:representation:builtin_types-gen.adoc#_class_boolean[Boolean] +
 +
  *post_cond* +
    result_validity: Result = eval_type().equal(BMM_MODEL.boolean_type_definition());

a|True if `eval_type` is notionally Boolean (i.e. a `BMM_SIMPLE_TYPE` with `type_name()`
= `Boolean`).

|===
