
[%autowidth.stretch]
|===

3+^h| abstract  *class EL_AGENT*


h|
2+^h|*Feature Group "access"*

h|prop +
  
|*name*: xref:representation:builtin_types-gen.adoc#_class_string[String]
a|Name of the routine being called.

h|prop +
  0..1
|*closed_args*: xref:languages:bmm-gen.adoc#_class_el_tuple[EL_TUPLE]
a|Closed arguments of a routine call as a tuple of objects.

h|prop +
  0..1
|*open_args*: xref:representation:builtin_types-gen.adoc#_class_list[List]<xref:representation:builtin_types-gen.adoc#_class_string[String]>
a|Optional list of names of open arguments of the call. If not provided, and the `name`
refers to a routine with more arguments than supplied in `closed_args`, the missing
arguments are inferred from the `definition`.

h|prop +
  0..1
|*definition*: xref:languages:bmm-gen.adoc#_class_bmm_routine[BMM_ROUTINE]
a|Reference to definition of a routine for which this is an agent, if one exists.

h|prop +
  
|*is_writable*: xref:representation:builtin_types-gen.adoc#_class_boolean[Boolean]
a|

h| func
|*eval_type* : xref:languages:bmm-gen.adoc#_class_bmm_routine_type[BMM_ROUTINE_TYPE] +
 +
  *post_cond* +
    result_validity: Result = definition.signature;

a|Eval type is the signature corresponding to the (remaining) open arguments and return
type, if any.

h| func
|*is_callable* : xref:representation:builtin_types-gen.adoc#_class_boolean[Boolean] +
 +
  *post_cond* +
    result_validity: Result = ¬ ∃ open_arguments;

a|True if there are no open arguments.

h| func
|*reference* : xref:representation:builtin_types-gen.adoc#_class_string[String]
a|Generated full reference name, including scoping elements.

h|prop +
  0..1
|*scoper*: xref:languages:bmm-gen.adoc#_class_el_value_generator[EL_VALUE_GENERATOR]
a|Scoping expression, which must be a `EL_VALUE_GENERATOR`.

h| func
|*is_boolean* : xref:representation:builtin_types-gen.adoc#_class_boolean[Boolean] +
 +
  *post_cond* +
    result_validity: Result = eval_type().equal(BMM_MODEL.boolean_type_definition());

a|True if `eval_type` is notionally Boolean (i.e. a `BMM_SIMPLE_TYPE` with `type_name()`
= `Boolean`).

|===
