
[%autowidth.stretch]
|===

3+^h|  *class EL_CASE_TABLE<T:EL_TERMINAL>*


h|
2+^h|*Feature Group "access"*

h|prop +
  
|*items*: xref:representation:builtin_types-gen.adoc#_class_list[List]<xref:languages:bmm-gen.adoc#_class_el_case[EL_CASE]<T>>
a|Members of the chain, equivalent to branches in an if/then/else chain and cases in a case
statement.

h|prop +
  
|*test_value*: xref:languages:bmm-gen.adoc#_class_el_value_generator[EL_VALUE_GENERATOR]
a|Expressing generating the input value for the case table.

h|prop +
  
|*else*: T
a|Result expression of conditional, if its `condition` evaluates to True.

h| func
|*eval_type* : xref:languages:bmm-gen.adoc#_class_bmm_type[BMM_TYPE]
a|Meta-type of expression entity used in type-checking and evaluation.

Effected in descendants.

h| func
|*is_boolean* : xref:representation:builtin_types-gen.adoc#_class_boolean[Boolean] +
 +
  *post_cond* +
    result_validity: Result = eval_type().equal(BMM_MODEL.boolean_type_definition());

a|True if `eval_type` is notionally Boolean (i.e. a `BMM_SIMPLE_TYPE` with `type_name()`
= `Boolean`).

|===
