
[%autowidth.stretch]
|===

3+^h|  *class EL_CONDITION_CHAIN<T:EL_TERMINAL>*

h|*Description*
2+a|Compound expression consisting of a chain of condition-gated expressions, and an ungated
`else` member that as a whole, represents an if/then/elseif/else chains.

Evaluated by iterating through `items` and for each one, evaluating its `condition`,
which if True, causes the evaluation result of the chain to be that item's `result`
evaluation result.

If no member of `items` has a True-returning `condition`, the evaluation result is the
result of evaluating the `else` expression.

h|*Inherit*
2+|xref:languages:bmm-gen.adoc#_class_el_decision_table[EL_DECISION_TABLE]

h|
2+^h|*Feature Group "access"*

h|prop +
  
|*items*: xref:representation:builtin_types-gen.adoc#_class_list[List]<xref:languages:bmm-gen.adoc#_class_el_conditional_expression[EL_CONDITIONAL_EXPRESSION]<T>>
a|Members of the chain, equivalent to branches in an if/then/else chain and cases in a case
statement.

h|prop +
  
|*else*: T
a|Result expression of conditional, if its `condition` evaluates to True.

h| func
|*eval_type* : xref:languages:bmm-gen.adoc#_class_bmm_type[BMM_TYPE]
a|Meta-type of expression entity used in type-checking and evaluation.

Effected in descendants.

h| func
|*is_boolean* : xref:representation:builtin_types-gen.adoc#_class_boolean[Boolean] +
 +
  *post_cond* +
    result_validity: Result = eval_type().equal(BMM_MODEL.boolean_type_definition());

a|True if `eval_type` is notionally Boolean (i.e. a `BMM_SIMPLE_TYPE` with `type_name()`
= `Boolean`).

|===
